export const ADD_CUSTOMER="ADD_CUSTOMER";
export const ADD_ITEM="ADD_ITEM";
export const GET_ITEM_BY_USER_ID="GET_ITEM_BY_USER_ID";
export const GET_CUSTOMER_BY_ID="GET_CUSTOMER_BY_ID";
export const ADD_TOTAL_TO_CUSTOMER="ADD_TOTAL_TO_CUSTOMER";
export const TOGGLE_CHECK="TOGGLE_CHECK;"